name: tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install AWS SAM cli
        uses: aws-actions/setup-sam@v1
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
#      - name: Run cargo test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
      - name: Build 
        run: make build
      - name: Test
        run: make test
