name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            target: aarch64-unknown-linux-gnu
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install AWS SAM cli
        uses: aws-actions/setup-sam@v1
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --lib --bins --target aarch64-unknown-linux-gnu
